name: Merge dev into main

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "yes" to confirm merge from dev to main'
        required: true

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Merge dev into main
        run: |
          if [ "${{ github.event.inputs.confirm }}" != "yes" ]; then
            echo "Confirmation not provided, aborting merge."
            exit 1
          fi
          git checkout main
          git merge --no-ff origin/dev
          git push origin main